import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyNav from "@/components/MyNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "nextjs202507050418dsa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navLists = [
    { label: "Home", href: "/" },
    { label: "Array", href: "/Array" },
    { label: "Linked List", href: "/LinkedList" },
    { label: "Stack", href: "/Stack" },
    { label: "Queue", href: "/Queue" },
    { label: "Recursion", href: "/Recursion" },
    { label: "Tree", href: "/Tree" },
    { label: "Hash Table", href: "/HashTable" },
    { label: "Trie", href: "/Trie" },
    { label: "Sort", href: "/Sort" },
    { label: "Search", href: "/Search" },
    { label: "Graph", href: "/Graph" },
    { label: "Algorithm", href: "/Algorithm" },
  ];
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MyNav navLists={navLists} />
        {children}
      </body>
    </html>
  );
}
